version: '3.8'

services:
  appserver:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: appserver
    command: gunicorn --bind 0.0.0.0:8000 appserver.wsgi --workers=4
    restart: always
    expose:
      - 8000
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - appserver-network
    env_file:
      - ./app/.env

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - appserver
    networks:
      - appserver-network

networks:
  appserver-network:
    name: appserver-network

volumes:
  media_volume:
  static_volume:
